### 列表转ndarray

In [2]:
# numpy中仅有一种数据类型-ndarray（N-DIMENSIONAL ARRAYS N维数组）
# 列表转ndarray
import numpy as np
list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [3]:
oneArray = np.array(list1)
print(type(oneArray))
# 类型是ndarray
print(oneArray)
# ndarray的特点是没有，
# ndarray的运算效率高于list

<class 'numpy.ndarray'>
[1 2 3 4]


### np.arange生成ndarray

In [4]:
import random
import numpy as np
# 等价于range(0,10,2),返回ndarray，range返回的是一个range对象，不能直接转换为ndarray
t3 = np.arange(0, 10, 2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


### 二维列表转ndarray

In [5]:
import numpy as np
list2 = [[1, 2], [3, 4], [5, 6]]
twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)
# 列表的输出是有逗号的，ndarray的输出是没有逗号的且会换行

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [6]:
# ndarray转换为列表
twoArray.tolist()

[[1, 2], [3, 4], [5, 6]]

### 常用属性

In [7]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

# 获取维度
twoArray = np.array(list2)

print(twoArray.ndim)

# 形状（行，列）
print(twoArray.shape)

# 元素个数
print(twoArray.size)

# 数据类型
print(twoArray.dtype)   #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int64


### 调整数组形状

In [8]:
four = np.array([[1, 2, 3], [4, 5, 6]])
# 在原有数组上改变形状，地址不变
four.shape = (3, 2)
# 改变后返回副本，地址改变
four2 = four.reshape(3, 2)

In [9]:
# 展平：将多维变成一维数组
five = four.reshape((6,), order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten()  # 展开成一维数组
#数组若改变行和列后，再变回原格式，其形式不变

In [10]:
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim)
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [11]:
# 转成三维
#最前面的[是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
#(2, 3, 4)其中2为轴0，3为轴1，4为轴2
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


### 数组转换为列表

In [12]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


## NumPy的数据类型

In [13]:
import random

f = np.array([1, 2, 3, 4], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型，节省空间，默认int32
print(f.itemsize)  # 1 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

1
int8


In [14]:
# 修改数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)  #显示字节数
print('-' * 50)

int64
8
--------------------------------------------------


In [15]:
random.random()  # 随机生成0-1之间的小数，若生成0-100，则可乘以100

0.03811928966629452

In [16]:
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(), 2))
# np.float16 半精度，可修改精度，但过高的用不上
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
# np语法，取小数点后两位
print(np.round(arr, 2))

0.06
[0.8757938  0.43016827 0.81076828 0.64672503 0.72209337 0.8175316
 0.83991046 0.35456983 0.73942244 0.07446444]
8
float64
[0.88 0.43 0.81 0.65 0.72 0.82 0.84 0.35 0.74 0.07]


## 数组和数的计算

In [17]:
# [1,2,3]+5

In [18]:
# numpy的广播机机制：加减乘除的值被广播到所有的元素上面
# 不能对列表进行直接加整数操作
# 无论多少维的ndarray都可以直接和一个常数进行运算
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
print(t1 + 2)
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


### ndarray与ndarray的运算

In [19]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #不是矩阵乘法，需要特殊接口


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [20]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)

ValueError: cannot reshape array of size 6 into shape (3,6)

In [ ]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等，即若行数或列数有一个不相等，但不相等的有一个是1（即一维），则会将其运算广播到全部空间
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2

In [ ]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2


In [ ]:
#随机3维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
a - b

结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1，则可进行广播运算

## 轴运算

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
# 按轴求和
print(np.sum(a, axis=0))
# 按哪个轴求和，哪个轴没了（求和降维）
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)


In [ ]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

## 索引和切片

In [ ]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引2开始到索引7停止，步长为2

# 只放置一个参数将返回与该索引相对应的单个元素
print(a[0], a)

# [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

#切片是左闭右开
print(a[2:8:2])


In [ ]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)

# 取一行
print(t1[1])
print('*' * 20)

# 取连续的多行
print(t1[1:])
print('*' * 20)

# 取连续的多行
print(t1[1:3, :])
print('*' * 20)

# 取不连续的多行
print(t1[[0, 2, 3]])

In [ ]:
# 取一列
print(t1[:, 1])
print('*' * 20)

# 连续的多列
print(t1[:, 1:])
print('*' * 20)

# 取不连续的多列
print(t1[:, [0, 2, 3]])
print('*' * 20)

# 取某一个值,三行四列
print(t1[2, 3])
print('*' * 20)

# 取多个不连续的值，[[行，行],[列，列]]
print(t1[[0, 1, 1], [0, 1, 3]])

t1[1:3, 1:4]  #取1-3行，1-4列

## 修改值

In [ ]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
#修改值为在原始数据上修改
print('-' * 50)

# 修改某一行的值
t[1,:]=0

# 修改某一列的值
t[:,1]=0

# 修改连续多行
t[1:3,:]=0

# 修改连续多列
t[:,1:4]=0

# 修改多行多列，取第二行到第四行，第三列到第五列
t[1:3,2:5]=0

# 修改多个不相邻的点
t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
t[t<10]=0

# 使用逻辑判断
# 逻辑与，and
t[(t>2)&(t<6)]=0

# 逻辑或，or
t[(t<2)|(t>6)]=0

# 逻辑非
t[~(t>6)]=0

t = t.clip(10, 18)
#clip 小于10的值变为10，大于18的值变为18
print(id(t))
t


In [ ]:
#三目运算
a = 10
b = 15
c = a if a > b else b
c

In [ ]:
# 类似
# 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)

## 数据的添加，删除与去重

### append插入

In [ ]:
'''
1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
此外，输入数组的维度必须匹配否则将生成ValueError。
参 数 说 明 ：                                                                                                    arr： 输 入 数 组                                                                                               values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                                            axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。当axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
#插入但未指明具体位置，则ndarray会被展平
#append返回副本，不改变自身
print(np.append(a, [7, 8, 9]))
print('\n')
print(a)
print('-' * 50)
#往哪个轴添加，那个轴size就变大
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)
print('-' * 50)

### insert 插入

In [ ]:
'''
 2. numpy.insert
 函数在给定索引之前，沿给定轴在输入数组中插入值。如果值的类型转换为要插入，则它与输入数组不同。
 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
'''

a = np.array([[1, 2], [3, 4], [5, 6]])

#未传递 Axis 参数。 在插入之前输入数组会被展开。
print(np.insert(a, 1, [11, 22]))
print('-' * 50)

#那个轴插入，哪个轴size变大
print(np.insert(a, 1, [11, 12], axis=0))
# 传递了 Axis 参数,但数据为一个单值，则会将该值在这一行进行填充
print(np.insert(a, 1, 11, axis=0))

print(np.insert(a, 1, [1, 2, 5], axis=1))

### 删除

In [ ]:
'''
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
如果未提供轴参数， 则输入数组将展开。
参 数 说 明 ：
arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''
import numpy as np

a = np.arange(12).reshape(3, 4)

# 未传递 Axis 参数。 在删除之前输入数组会被展开。
print(np.delete(a, 5))

#删除第一行
print(np.delete(a, 1, axis=0))

#删除第一列
print(np.delete(a, 1, axis=1))

### 去重

In [ ]:
'''
numpy.unique 函数用于去除数组中的重复元素。
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

# 去除重复元素，输出的是有序序列
# u = np.unique(a)
# print (u)
# print ('\n')

# 去重后数组在原数据中的索引位置
# u,indices = np.unique(a, return_index = True)
# print(u)
# print (indices)
# print ('\n')

# 显示去重前的样本数据在去重后的数据中对应的下标位置
# u,indices = np.unique(a,return_inverse = True)
# print (u)
# print (indices)
# print ('\n')

# 显示去重元素的重复数量
# u, indices = np.unique(a, return_counts=True)
# print(u)
# print(indices)

## 数学计算

In [ ]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
# 1. 数据最大值
result = np.max(score)
print(result)

# 2. 某一个轴上的数据最大值，得到后对应的轴就消失，仅留下降维后的最大值
result = np.max(score, axis=1)
print(result)

# 3. 最小值
result = np.min(score)
print(result)

# 4. 某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)

# 5. 数据的比较
# 第一个参数中的每一个数与第二个参数比较返回大的
result = np.maximum([-2, -1, 0, 1, 2], 0)
print(result)

# 第一个参数中的每一个数与第二个参数比较返回小的
result = np.minimum([-2, -1, 0, 1, 2], 0)
print(result)

# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，是用到了维度的广播机制
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)

# 6.求平均值
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)

# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# 行
print(arr.cumsum(axis=0))
# 列
print(arr.cumsum(axis=1))

# 8. argmin求最小值对应的索引
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)
print(result, res)

# 9. 求每一列的标准差
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大。一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score, axis=0)
print(result)

# 10. 极值（最大值和最小值的差）
result = np.ptp(score, axis=None)
print(result)
# 其他方法：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

# 数学函数

In [ ]:
'''
其他通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

## 数组拼接

In [ ]:
import numpy as np

# 1. 根据轴连接的数组序列，concatenate不会改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
# # 要求a,b两个数组的维度相同

#写哪个轴，哪个轴就变化
# 0：横向连接
print(np.concatenate((a, b), axis=0))
print('-' * 50)
# 1：纵向连接
print(np.concatenate((a, b,c), axis=1))

In [ ]:
# 2. stack 根据轴进行堆叠，会增加维度，2维会变为3维，按哪个轴堆叠，哪个轴就会变为堆叠的个数
print(np.stack((a, b,c), axis=1).shape)
arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
print(len(arrays))
# 沿轴 0 连接两个数组
result0 = np.stack(arrays, axis=0)
# 沿轴 1 连接两个数组
result1 = np.stack(arrays, axis=1)
# 这里-1与2等价，表示最大的轴数
result2 = np.stack(arrays, axis=-1)

In [ ]:
# 3. vstack，矩阵垂直拼接，没有增加维数，类似于concatenate（concatenate为轴0，vstack为轴1方向）用的很少
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

# # # 4. 矩阵水平拼接，类似于concatenate  horizontal
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

## 分割

In [ ]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
import numpy as np

arr = np.arange(12).reshape(4, 3)
print(arr)
#  按那个轴切，那个轴发生变化，将数组分为三个大小相等的子数组
b = np.split(arr, 3, axis=1)
print(b)

In [ ]:
# 随机，效率更高
d = np.random.random((2, 6))

In [ ]:
# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10 * np.random.random((2, 6)))
# 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4, 4)
# 竖直分割
b = np.vsplit(a, 2)
print(b)

## inf和nan

In [ ]:
'''
inf: 无穷大
nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
任何与其做运算结果都是 nan
np.nan != np.nan	结果是TRUE
'''
import numpy as np

# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

In [ ]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)

# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
print(t != t)
print('-' * 50)

# 可以使用np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t != t))  # 统计nan的个数，t!=t为true，即非零


In [ ]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

In [ ]:
# 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 初始化数组，将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('------------------------------')
# 遍历每一列，然后判断每一列是否有nan
# t.shape[1]为拿其列数，t.shape为其形状属性，[1]则为列数
for i in range(t.shape[1]):
    # 切片，获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan/使用isnan判断也可
    nan_num = np.count_nonzero(temp_col != temp_col)

    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]

        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)
# 前后地址不变

In [21]:
# inf与inf 是相等的
print(np.inf == np.inf)
np.inf

True


inf

In [23]:
arr = np.array([-1, 0])
print(arr)
# 1除0就会得到inf
print(arr[0] / arr[1])

[-1  0]
-inf


C:\Users\DELL\AppData\Local\Temp\ipykernel_9696\2586930737.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])  #1除0就会得到inf


In [24]:
# nan与inf运算结果还是nan
np.nan + np.inf

nan

## 转置和轴滚动

In [27]:
#对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
# transpose返回副本
print(np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3, 4)

# a.T也是返回副本
print(a.T)
print(a)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
# swapaxes用于交换数组的两个轴，对于二维数组来说相当于转置
re1 = t1.swapaxes(1, 0)

In [ ]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)

# 三维以上为轴交换（交换仅做计算，还会换回来）
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)

In [ ]:
# 轴滚动,swapaxes每次只能交换两个轴，rollaxis更方便，无参数三默认情况下轴滚动最前面
# 参数二为要滚动轴几，滚动到参数三位置之前
a = np.ones((3, 4, 5, 6))
np.rollaxis(a, 2).shape
np.rollaxis(a, 3, 1).shape

In [ ]:
#copy()地址不同和赋值地址相同
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
a

In [ ]:
b[0, 0] = 3
print(b)
a

In [ ]:
#随机数生成，可生成多种随机数
arr = np.random.rand(2, 3, 4)
print(arr)

In [ ]:
'''
创建d0-dn维度的均匀分布的随机数数组,浮点数,范围从0-1
.rand(d0, d1, .. dn)

创建d0-dn维度的标准正态分布随机数,浮点数,平均数0,标准差1
.randn(d0,d1, .. dn)

从给定上下限范围选取随机数整数,范围是low,high,形状是shape
.randint (low, high,(shape))


产生具有均匀分布的数组,low起始值,high结束值,size形状
.uniform(low, high,(size))

从指定正态分布中随机抽取样本,分布中心是loc(概率分布的均值),标准差是scale,形状是size
.normal(loc, scale,(size))


随机数种子,s是给定的种子值。因为计算机生成的是伪随机数,所以通过设定相同的随机数种子,可以每次生成相同的随机数
. seed (s)

'''